### ISSUE TITLE
Fields test fails

### ISSUE THREAD

**Issue by dawidd6** [gcla/termshark#24]
```
=== RUN   TestFields1
--- FAIL: TestFields1 (1.09s)
    fields_test.go:18: 
                Error Trace:    fields_test.go:18
                Error:          Received unexpected error:
                                open /home/builder/.cache/termshark/tsharkfields.gob.gz: no such file or directory
                Test:           TestFields1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x87754d]

goroutine 20 [running]:
testing.tRunner.func1(0xc0000e8600)
        /usr/lib/go-1.11/src/testing/testing.go:792 +0x387
panic(0x8f4340, 0xd3c630)
        /usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
github.com/gcla/termshark.TestFields1(0xc0000e8600)
        /build/source/_build/src/github.com/gcla/termshark/fields_test.go:20 +0xad
testing.tRunner(0xc0000e8600, 0x98efb8)
        /usr/lib/go-1.11/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
        /usr/lib/go-1.11/src/testing/testing.go:878 +0x35c
FAIL    github.com/gcla/termshark       1.114s
```

This only happens if termshark wasn't run before.
Simply executing `termshark -h` and then running tests, resolves this issue.

UPDATE: Okay after more investigation, it seems like the problem is about non existing `termshark` directory in `$XDG_CONFIG_CACHE`.

**Comment by gcla** [comment]
Thanks for debugging, I'll fix this.
